[package]
name = "hg-core"
version = "0.1.0"
authors = ["Georges Racinet <gracinet@anybox.fr>"]
description = "Mercurial pure Rust core library, with no assumption on Python bindings (FFI)"
edition = "2018"

[lib]
name = "hg"

[dev-dependencies]
rand = "*"
rand_pcg = "*"

[dependencies]
byteorder = "1.3.1"
lazy_static = "1.3.0"
memchr = "2.2.0"
regex = "^1.1"
